version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - webnet
  web:
    build: .
    volumes:
      - .:/oj
      - /oj/node_modules
    links:
      - redis:redis
    env_file:
      - .env
    networks:
      - webnet
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    ports:
      - 3000:3000
networks:
  webnet:




# version: '3'
# services:
#   redis:
#     image: "redis:alpine"
#     ports:
#       - "6379:6379"
#     expose:
#       - 6379
#     networks:
#       - webnet
#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/oj
#       - /oj/node_modules
#     links:
#       - redis:redis
#     env_file:
#       - .env
#     networks:
#       - webnet
# networks:
#   webnet:
