version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - webnet
  web:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - redis:redis
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet:
